### ISSUE TITLE
Keep the original order for continuous background tabs

### ISSUE THREAD

**Issue by Keith94** [autonome/Always-Right#11]
I like how this add-on prevent tabs from opening way at the end of the tab bar; but I also wish that the original order of new tabs would be respected too, i.e. *new tab 1* should be inserted after current tab, and *new tab 2* should be inserted after new tab 1 rather than before it. This is how Firefox normally handles opening new links. Can this be implemented? Most notably opening new bookmarks via toolbar does not use the original order with this add-on installed.

**Comment by autonome** [comment]
Hmmmm, interesting. I'm not sure I want that in *this* addon, as it's
called *always* right for a reason ;)

But can you explain the toolbar scenario in a series of steps you're
taking? I don't understand it.

Also, I think it's not actually possible until this ships:
https://bugzilla.mozilla.org/show_bug.cgi?id=1238314

**Comment by Keith94** [comment]
Well, for the bookmarks toolbar:

1. Change `browser.tabs.loadBookmarksInBackground` to `true`
1. Open Bookmark 1 in new tab
2. Open Bookmark 2 in new tab

For me, the order of the tab bar looks like: `Original tab | Bookmark 2 | Bookmark 1`

But with web page links it seems the results are different? Opening Link 1 and Link 2 will result in the order: `Original tab | Link 1 | Link 2`

I hope that makes sense. Keeping the original order makes more sense for my workflow, but I didn't find an add-on that can quite do it yet.

**Comment by autonome** [comment]
Wow, yeah I have no idea how all this would play together with non-default
prefs flipped.

The tab order difference you're seeing is likely because "opener"
relationship isn't set when opening a bookmark from the toolbar (or
anywhere else). That's because there's no relation between the active tab
and the bookmarks you're opening - you just happened to have that tab
active at the time.

There's a crazy decision-tree that happens when opening new tabs... which
is the cause for this extension in the first place: Deterministic.
Predictable. No aberration.

Which is why I think what you're asking for should be a different extension
altogether.

The code for this extension is pretty simple. Once the opener functionality
lands, you could probably copy it and hack a version together that does
what you're asking.

**Comment by Keith94** [comment]
All right, that answers my question. Thanks for reply :)
