### ISSUE TITLE
Fall back to front of the list

### ISSUE THREAD

**Issue by kumar303** [autonome/Always-Right#15]
Hi! I've noticed that very occasionally a new tab gets opened at the end of my tab list. There is probably a bug somewhere but I haven't been able to reproduce it. 

It made me wonder, could it fall back to the front of the list for any case where the rightmost-position can't be known? I think that more or less matches the use case for this extension, i.e. your last task is most likely at the front of the tab list.

**Comment by autonome** [comment]
Hm, that's a pretty big assumption for anyone with a decent number of tabs
open.

There's only a single case where I change the new tab's index to something
other than "currentTab.index + 1", and that's when the current tab is a
pinned tab. In that case, I do some hijinks around finding the *last*
pinned tab and placing the new tab to the right of it. Maybe a bug in that
code...

Can you keep an eye out for when this happens and see if it's because you
were on a pinned tab?

**Comment by kumar303** [comment]
Aha, I think I know what it is. It happens after I restart for a Nightly update if the first thing I do is open a link from an external application. The tab I was session-restored was not a pinned tab last time it happened, I think.

**Comment by kumar303** [comment]
Well, huh, I just tried to replicate it with that theory and it didn't work. Ha.

**Comment by autonome** [comment]
This should be fixed with Firefox 61 now that #22 is landed, which uses the official built-in support for tab placement.
